export const content = {
    welcomeBack: 'Welcome back',
    form: {
        descriptionLoginTitle: 'Login form',
        descriptionLoginBody: 'Please, input your username and phone number',
        namePlaceholder: 'Username',
        phonePlaceholder: 'Phone',
        login: 'Login',
        logout: 'Log out',
        errorOnlyLetters: 'Only letters',
        errorUsernameRequired: 'Username is required',
        errorOnlyNumbersSymbols: 'Only numbers and symbols',
        errorTelephoneRequired: 'Telephone is required',
        errorLoginError: 'Login error',
    },
    filter: {
        byStatus: 'By status',
        allUsers: 'All users',
        searchByTitle: 'Search by title',
    },
    todos: {
        title: 'Todo list',
        createTodoTitle: 'Create todo',
        addTodo: 'Add',
        id: 'Id',
        userId: 'User id',
        todoTitle: 'Todo title',
        completed: 'Completed',
        favorites: 'Favorites',
        noTodosFound: 'No todos found',
    },
    html: {
        favoriteMarkChecked: '&#9733;',
        favoriteMark: '&#9734;',
        completedMark: '&#10003;',
        refreshFilters: '&#10226;',
    },
}
